# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.4.1a3
_src_path: gh:Gehock/python-template
author_email: sami.v.laine@gmail.com
author_name: Sami Laine
description: Operations bot for the Zeusops discord
project_name: Operation Bot
project_slug: operationbot
python_version: '3.11'
