# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.1-2-g705747a
_src_path: gh:OverkillGuy/python-template
author_email: sami.v.laine@gmail.com
author_name: Sami Laine
description: Operations bot for the Zeusops discord
package_name: operationbot
project_name: Operation Bot
project_slug: operationbot
python_version: '3.11'
