---
name: pre-commit

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  pre-commit:
    # Name the Job
    name: Run pre-commit
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Copy secret.py
      run: |
        cp secret.py.example src/operationbot/secret.py
    - uses: pre-commit-ci/lite-action@v1.0.0
      if: always()
